FROM ubuntu

MAINTAINER huller <huller@student.21-school.ru>

RUN apt-get update && \
        apt-get upgrade -y && \
        apt-get install -y default-jdk default-jre git vim emacs

# docker build -t 04 .
# docker run --rm -ti 04
