FROM debian

MAINTAINER huller <huller@student.21-school.ru>

RUN apt-get update && \
        apt-get upgrade -y && \
        apt-get install -y build-essential git vim

# docker build -t 01 .
# docker run --rm -ti 01
